version: '3.3'
services:


  my-first-bot:
    image: dedrobin/my-first-bot:latest
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    environment:
      - BOT_TOKEN=$BOT_TOKEN
    command: |
      python server.py
#  my-first-bot-2:
#    image: dedrobin/my-first-bot-2:latest
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./:/app/
#    environment:
#      - BOT_TOKEN=$BOT_TOKEN
#    command: |
#      python bots.py
