version: '3.3'
services:
  redis:
    image: redis:latest
  bot-server: &base_container
    image: bot:latest
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=$BOT_TOKEN
    command: |
      python server.py

  handler:
    <<: *base_container
    ports: [ ]
    command: |
      python bots.py
