version: '3.3'
services:
  redis:
    image: redis:latest

  bot-server: &base_container
    image: dedrobin/bot:latest
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - REDIS_HOST=redis
    command: |
      python server.py

  handler:
    <<: *base_container
    ports:
      [ ]
    command: |
      python bots.py
